
version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "9090:9090"
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5433
      DATABASE_NAME: testdb
      DATABASE_USER: user
      DATABASE_PASSWORD: password

volumes:
  db_data:
