services:
  postgres:
    image: postgres
    container_name: my_postgres
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: my_db
    restart: always